# Generated by Django 4.2.10 on 2024-02-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
